### PR TITLE
Added a line on military or violence metaphors

### PR DESCRIPTION
**Pull request by nllz**

### CODE REVIEW

**Comment by ekr** [comment]
This seems like overreaching. This document will work best if it stays to the core areas of inclusion.

I would note in particular that "terminate" just straightforwardly means "end" and the use in military contexts is itself euphemistic.

**Comment by nllz** [comment]
May I respond by suggesting that violent and militaristic metaphors can be equally triggering and excluding in a similar manner as  the other examples. 

If people think that 'terminate' can also be understood outside of a militaristic context, I'd be happy to drop that from the examples.

**Comment by bifurcation** [comment]
"Terminate" is regularly used for "to end", especially for things like contracts.  How many "terminals" have IETF attendees been through that are just supposed to be the end of (one segment of) a journey.

"Kill" seems worth considering alternatives for, though.  Perhaps we could narrow to just that?

**Comment by nllz** [comment]
Removed 'terminate' as suggested.

**Comment by nllz** [comment]
Can this be merged?

**Pull request merged**
